---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-postgresql-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-postgresql-app
  template:
    metadata:
      labels:
        app: spring-postgresql-app
        deploymentconfig: spring-postgresql-app
    spec:
      containers:
        - name: spring-postgresql-app
          image: quay.io/ecosystem-appeng/spring-postgresql-demo:v0.0.1
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-postgresql-app
  name: spring-postgresql-app
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: spring-postgresql-app
    deploymentconfig: spring-postgresql-app
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: spring-postgresql-app
  name: spring-postgresql-app
spec:
  to:
    kind: Service
    name: spring-postgresql-app
